# trivial change
language: node_js

services:
  - docker

branches:
  only:
    - master

script:
  - docker build -t martinseanhunt/docker-travis .
  - docker ps -a
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push martinseanhunt/docker-travis
