apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-depl
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: simple-node
          image: martinseanhunt/docker-travis
          # checks a given endpoint to see if the server is running
          # if it fails k8s will recreate it to maintain the number of desired replicas
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-srv
  labels:
    app: my-app
spec:
  type: ClusterIP
  ports:
    - name: my-app-srv-port
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-app
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-depl
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
