apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-depl
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: simple-node
          image: martinseanhunt/docker-travis
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-srv
  labels:
    app: my-app
spec:
  type: ClusterIP
  ports:
    - name: my-app-srv-port
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-app
